Import('env')

env1 = env.Clone()

tests = " ".join(ARGUMENTS.get('tests', '').split(','))

env1['ENV']['LD_LIBRARY_PATH'] = 'build/src'
env1['ENV']['PYTHONPATH'] = 'build/bindings:test'

test_nodes = []
test_nodes.append(env1.Command(None, 'run_tests.py', "python $SOURCE %s" % tests));

Return('test_nodes')
