import os
import distutils

Import('env')

bindings = " ".join(ARGUMENTS.get('bindings', '').split(','))

libs = {}

if 'lua' in bindings:
	l = env.SharedLibrary('bless_buffer_${lib_major}_${lib_minor}.so', ['bless_buffer_lua.c'],
			LIBS = ['$lib_name_no_lib'], LIBPATH = '#build/src',
			CPPFLAGS = ['-DLIBBLS_VERSION_MAJOR=${lib_major}', '-DLIBBLS_VERSION_MINOR=${lib_minor}'],
			CPPPATH = ['$lua_CPPPATH', '../src'], SHLIBPREFIX = ' ')

	libs['lua'] = l
	
if 'python' in bindings or 'test' in BUILD_TARGETS:
	env = env.Clone(SWIGFLAGS = ['-python'])

	source = Glob('*.i')

	for f in source:
		(fn, ext) = os.path.splitext(os.path.basename(f.get_path()))
		l = env.SharedLibrary(fn, [f], LIBS = ['$lib_name_no_lib'],
				LIBPATH = '#build/src', 
				CPPPATH=['$PYTHON_INCLUDE_PATH', '../src'], SHLIBPREFIX='_')
		libs['python'] = l


Return('libs')
