import os
import scons_helpers

Import('env')

source = Glob('*.c')

# Create shared library
lib = scons_helpers.versioned_library(env.subst('$lib_filename'), 
	source, env.subst('$lib_soname'), env)

Return('lib')
