import os
import scons_helpers

Import('env')

source = Glob('*.c')

# Create shared library
libbless = scons_helpers.versioned_library(env.subst('$libbless_filename'), 
	source, env.subst('$libbless_soname'), env)

Return('libbless')
